version: '3'
services:
  devenv:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    depends_on:
      - mongo
      - dynamodb
  mongo:
    image: mongo
    ports:
     - 27017:27017
  dynamodb:
    image: amazon/dynamodb-local
    ports:
     - 8000:8000