version: '3'
services:
  devenv:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    command: sleep infinity
    volumes:
      - ..:/workspace
    depends_on:
      - azurecosmosdb
      - azurestorage
      - sql
      - dynamodb
      - mongo
  azurecosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    ports:
      - 8081:8081
  azurestorage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10002:10002
  sql:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
  mongo:
    image: mongo
    ports:
      - 27017:27017